# Generated by Django 5.2.1 on 2026-06-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('report_type', models.CharField(blank=True, default='Bug', max_length=64)),
                ('priority', models.CharField(blank=True, default='Normal', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
                ('reporter', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='Open', max_length=32)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_area', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_area_color', models.CharField(blank=True, default='', max_length=32)),
                ('instrument_type', models.CharField(blank=True, default='', max_length=64)),
                ('functions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Session', max_length=255)),
                ('analyst', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.CharField(blank=True, default='', max_length=255)),
                ('document_date', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('uut_description', models.CharField(blank=True, default='', max_length=255)),
                ('uut_tolerance', models.JSONField(blank=True, default=dict)),
                ('uncertainty_confidence', models.FloatField(default=95)),
                ('reliability', models.FloatField(default=85)),
                ('cal_int', models.FloatField(default=12)),
                ('meas_rel_calc_assumed', models.FloatField(default=85)),
                ('needed_tur', models.FloatField(default=4)),
                ('req_pfa', models.FloatField(default=2)),
                ('guard_band_multiplier', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_images', to='uncertainty.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_areas', to='uncertainty.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTmde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.FloatField(default=1)),
                ('asset_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_instrument_based', models.BooleanField(default=False)),
                ('instrument', models.JSONField(blank=True, default=dict, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmdes', to='uncertainty.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('tmde_description', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_area_id', models.CharField(blank=True, default='', max_length=64)),
                ('associated_uut_ids', models.JSONField(blank=True, default=list)),
                ('test_point_info', models.JSONField(blank=True, default=dict)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('measurement_type', models.CharField(default='direct', max_length=32)),
                ('equation_string', models.TextField(blank=True, default='')),
                ('variable_mappings', models.JSONField(blank=True, default=dict)),
                ('uut_tolerance', models.JSONField(blank=True, default=dict, null=True)),
                ('tmde_tolerances', models.JSONField(blank=True, default=list)),
                ('is_detailed_uncertainty_calculated', models.BooleanField(default=False)),
                ('combined_uncertainty', models.FloatField(blank=True, null=True)),
                ('combined_uncertainty_absolute_base', models.FloatField(blank=True, null=True)),
                ('combined_uncertainty_inputs_native', models.FloatField(blank=True, null=True)),
                ('combined_uncertainty_inputs_base', models.FloatField(blank=True, null=True)),
                ('effective_dof', models.FloatField(blank=True, null=True)),
                ('k_value', models.FloatField(blank=True, null=True)),
                ('expanded_uncertainty', models.FloatField(blank=True, null=True)),
                ('expanded_uncertainty_absolute_base', models.FloatField(blank=True, null=True)),
                ('calculated_nominal_value', models.FloatField(blank=True, null=True)),
                ('calculated_budget_components', models.JSONField(blank=True, default=list, null=True)),
                ('risk_metrics', models.JSONField(blank=True, default=dict, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_points', to='uncertainty.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ManualComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('component_type', models.CharField(blank=True, default='B', max_length=8)),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_native', models.FloatField(blank=True, null=True)),
                ('unit_native', models.CharField(blank=True, default='', max_length=64)),
                ('dof', models.FloatField(blank=True, null=True)),
                ('distribution', models.CharField(blank=True, default='', max_length=64)),
                ('is_core', models.BooleanField(default=False)),
                ('source_point_label', models.CharField(blank=True, default='', max_length=255)),
                ('variable_type', models.CharField(blank=True, default='', max_length=64)),
                ('original_input', models.JSONField(blank=True, default=dict, null=True)),
                ('saved_inputs', models.JSONField(blank=True, default=dict, null=True)),
                ('test_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='uncertainty.testpoint')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Uut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_area_cid', models.CharField(blank=True, default='', max_length=64)),
                ('measurement_area', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_area_color', models.CharField(blank=True, default='', max_length=32)),
                ('instrument', models.JSONField(blank=True, default=dict, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuts', to='uncertainty.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
