# Generated by Django 5.2.1 on 2026-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncertainty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpoint',
            name='input_correlations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
