# Generated by Django 5.2.1 on 2026-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncertainty', '0004_testpoint_coverage_factor_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEquation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('expression', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('measurement_area', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_area_color', models.CharField(blank=True, default='', max_length=32)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['measurement_area', 'name'],
            },
        ),
    ]
