# Generated by Django 5.2.1 on 2025-08-26 15:53

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default=api.models.get_default_cal_session_name, max_length=255, unique=True)),
                ('standard_instrument_model', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_instrument_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_reader_model', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_reader_address', models.CharField(blank=True, max_length=100, null=True)),
                ('test_instrument_model', models.CharField(blank=True, max_length=100, null=True)),
                ('test_instrument_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('test_reader_model', models.CharField(blank=True, max_length=100, null=True)),
                ('test_reader_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ac_source_address', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_source_address', models.CharField(blank=True, max_length=100, null=True)),
                ('switch_driver_address', models.CharField(blank=True, max_length=100, null=True)),
                ('switch_driver_model', models.CharField(blank=True, max_length=100, null=True)),
                ('amplifier_address', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative Humidity in %RH', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=5, max_digits=10)),
                ('frequency', models.IntegerField()),
                ('direction', models.CharField(choices=[('Forward', 'Forward'), ('Reverse', 'Reverse')], default='Forward', max_length=10)),
            ],
            options={
                'ordering': ['frequency', 'current', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='TVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('test_voltage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_shunt_range', models.FloatField(blank=True, null=True)),
                ('amplifier_range', models.FloatField(blank=True, null=True)),
                ('tvc_upper_limit', models.FloatField(blank=True, null=True)),
                ('calibration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='api.calibration')),
            ],
        ),
        migrations.AddField(
            model_name='calibration',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='api.calibrationsession'),
        ),
        migrations.CreateModel(
            name='CalibrationTVCCorrections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrections_data', models.JSONField(blank=True, default=dict)),
                ('calibration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tvccorrections', to='api.calibration')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.FloatField()),
                ('current', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('correction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('range', 'current', 'frequency')},
            },
        ),
        migrations.CreateModel(
            name='Shunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('range', models.FloatField()),
                ('current', models.FloatField()),
            ],
            options={
                'unique_together': {('serial_number', 'range', 'current')},
            },
        ),
        migrations.CreateModel(
            name='CalibrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_warm_up_time', models.IntegerField(blank=True, null=True)),
                ('num_samples', models.IntegerField(blank=True, default=8, null=True)),
                ('settling_time', models.IntegerField(blank=True, default=5, null=True)),
                ('nplc', models.FloatField(blank=True, default=20, help_text='Integration time in Power Line Cycles for 34420A', null=True)),
                ('stability_window', models.IntegerField(blank=True, default=5, null=True)),
                ('stability_threshold_ppm', models.FloatField(blank=True, default=10, null=True)),
                ('stability_max_attempts', models.IntegerField(blank=True, default=50, null=True)),
                ('test_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.testpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_ac_open_avg', models.FloatField(blank=True, null=True)),
                ('std_ac_open_stddev', models.FloatField(blank=True, null=True)),
                ('std_dc_pos_avg', models.FloatField(blank=True, null=True)),
                ('std_dc_pos_stddev', models.FloatField(blank=True, null=True)),
                ('std_dc_neg_avg', models.FloatField(blank=True, null=True)),
                ('std_dc_neg_stddev', models.FloatField(blank=True, null=True)),
                ('std_ac_close_avg', models.FloatField(blank=True, null=True)),
                ('std_ac_close_stddev', models.FloatField(blank=True, null=True)),
                ('ti_ac_open_avg', models.FloatField(blank=True, null=True)),
                ('ti_ac_open_stddev', models.FloatField(blank=True, null=True)),
                ('ti_dc_pos_avg', models.FloatField(blank=True, null=True)),
                ('ti_dc_pos_stddev', models.FloatField(blank=True, null=True)),
                ('ti_dc_neg_avg', models.FloatField(blank=True, null=True)),
                ('ti_dc_neg_stddev', models.FloatField(blank=True, null=True)),
                ('ti_ac_close_avg', models.FloatField(blank=True, null=True)),
                ('ti_ac_close_stddev', models.FloatField(blank=True, null=True)),
                ('eta_std', models.FloatField(blank=True, help_text='Gain factor for Standard instrument system', null=True)),
                ('eta_ti', models.FloatField(blank=True, help_text='Gain factor for Test Instrument system', null=True)),
                ('delta_std', models.FloatField(blank=True, help_text='Known AC-DC difference of the Standard TVC in PPM', null=True)),
                ('delta_ti', models.FloatField(blank=True, help_text='Known AC-DC difference of the TI TVC in PPM', null=True)),
                ('delta_std_known', models.FloatField(blank=True, help_text='Known AC-DC difference of the Standard Shunt in PPM', null=True)),
                ('delta_uut_ppm', models.FloatField(blank=True, help_text='Final calculated UUT AC-DC difference in PPM -> Forward or Revers', null=True)),
                ('delta_uut_ppm_avg', models.FloatField(blank=True, help_text='Final averaged UUT AC-DC difference in PPM', null=True)),
                ('combined_uncertainty', models.FloatField(blank=True, help_text='Calculated combined standard uncertainty (uc) in PPM', null=True)),
                ('effective_dof', models.FloatField(blank=True, help_text='Calculated effective degrees of freedom (veff)', null=True)),
                ('k_value', models.FloatField(blank=True, help_text='Calculated coverage factor (k)', null=True)),
                ('expanded_uncertainty', models.FloatField(blank=True, help_text='Calculated expanded uncertainty (U) in PPM', null=True)),
                ('is_detailed_uncertainty_calculated', models.BooleanField(default=False)),
                ('manual_uncertainty_components', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.testpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_ac_open_readings', models.JSONField(blank=True, default=list, null=True)),
                ('std_dc_pos_readings', models.JSONField(blank=True, default=list, null=True)),
                ('std_dc_neg_readings', models.JSONField(blank=True, default=list, null=True)),
                ('std_ac_close_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_ac_open_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_dc_pos_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_dc_neg_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_ac_close_readings', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.testpoint')),
            ],
        ),
        migrations.CreateModel(
            name='TestPointSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_point_set', to='api.calibrationsession')),
            ],
        ),
        migrations.AddField(
            model_name='testpoint',
            name='test_point_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.testpointset'),
        ),
        migrations.CreateModel(
            name='Uncertainty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.FloatField()),
                ('current', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('range', 'current', 'frequency')},
            },
        ),
        migrations.CreateModel(
            name='ShuntCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('correction', models.FloatField(blank=True, null=True)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('shunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='api.shunt')),
            ],
            options={
                'unique_together': {('shunt', 'frequency')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='testpoint',
            unique_together={('test_point_set', 'current', 'frequency', 'direction')},
        ),
        migrations.CreateModel(
            name='TVCCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('ac_dc_difference', models.IntegerField()),
                ('expanded_uncertainty', models.IntegerField()),
                ('tvc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='api.tvc')),
            ],
            options={
                'unique_together': {('tvc', 'frequency')},
            },
        ),
    ]
