# Generated by Django 5.2.1 on 2025-06-13 15:28

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default=api.models.get_default_cal_session_name, max_length=255, unique=True)),
                ('test_instrument_model', models.CharField(blank=True, max_length=100, null=True)),
                ('test_instrument_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_instrument_model', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_instrument_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative Humidity in %RH', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPointSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField(default=list)),
                ('ac_shunt_range', models.FloatField(blank=True, null=True)),
                ('tvc_upper_limit', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_point_set', to='api.calibrationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
