# Generated by Django 5.2.3 on 2025-06-17 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='api.calibrationsession')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_warm_up_time', models.IntegerField(blank=True, null=True)),
                ('num_samples', models.IntegerField(blank=True, null=True)),
                ('calibration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.calibrationsession')),
            ],
        ),
    ]
