# Generated by Django 5.2.1 on 2025-10-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correction',
        ),
        migrations.DeleteModel(
            name='Uncertainty',
        ),
        migrations.AlterModelOptions(
            name='testpoint',
            options={'ordering': ['order', 'frequency', 'current', 'direction']},
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='ac_source_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='amplifier_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='dc_source_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='standard_reader_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='standard_tvc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='switch_driver_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_reader_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_tvc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shunt',
            name='model_name',
            field=models.CharField(default='Shunt', max_length=100),
        ),
        migrations.AddField(
            model_name='shunt',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testpoint',
            name='order',
            field=models.IntegerField(default=0, help_text='Custom sort order for the test point pair'),
        ),
    ]
