# Generated by Django 5.2.1 on 2025-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correction',
        ),
        migrations.DeleteModel(
            name='Uncertainty',
        ),
        migrations.AddField(
            model_name='shunt',
            name='model_name',
            field=models.CharField(default='Shunt', max_length=100),
        ),
    ]
