# Generated by Django 5.2.3 on 2025-06-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calibration_calibrationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationsettings',
            name='calibration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.calibration'),
        ),
    ]
