# Generated by Django 5.2.1 on 2025-08-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_correction_delete_uncertainty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shunt',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
