# Generated by Django 5.2.1 on 2025-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_calibrationsettings_calibration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpointset',
            name='ac_shunt_range',
        ),
        migrations.RemoveField(
            model_name='testpointset',
            name='tvc_upper_limit',
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='ac_shunt_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='tvc_upper_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
