# Generated by Django 5.2.1 on 2025-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testpointset_delete_testpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpointset',
            name='ac_shunt_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testpointset',
            name='tvc_upper_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
