# Generated by Django 5.2.1 on 2025-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calibrationsettings_iqr_filter_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='stability_check_method',
            field=models.CharField(choices=[('sliding_window', 'Sliding Window'), ('iqr_filter', 'IQR Filter')], default='sliding_window', max_length=20),
        ),
    ]
