# Generated by Django 5.2.1 on 2025-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shunt_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='standard_tvc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_tvc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
