# Generated by Django 5.2.1 on 2025-06-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_testpointset_ac_shunt_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_ac_open_avg', models.FloatField(blank=True, null=True)),
                ('std_ac_open_stddev', models.FloatField(blank=True, null=True)),
                ('std_dc_pos_avg', models.FloatField(blank=True, null=True)),
                ('std_dc_pos_stddev', models.FloatField(blank=True, null=True)),
                ('std_dc_neg_avg', models.FloatField(blank=True, null=True)),
                ('std_dc_neg_stddev', models.FloatField(blank=True, null=True)),
                ('std_ac_close_avg', models.FloatField(blank=True, null=True)),
                ('std_ac_close_stddev', models.FloatField(blank=True, null=True)),
                ('ti_ac_open_avg', models.FloatField(blank=True, null=True)),
                ('ti_ac_open_stddev', models.FloatField(blank=True, null=True)),
                ('ti_dc_pos_avg', models.FloatField(blank=True, null=True)),
                ('ti_dc_pos_stddev', models.FloatField(blank=True, null=True)),
                ('ti_dc_neg_avg', models.FloatField(blank=True, null=True)),
                ('ti_dc_neg_stddev', models.FloatField(blank=True, null=True)),
                ('ti_ac_close_avg', models.FloatField(blank=True, null=True)),
                ('ti_ac_close_stddev', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.calibration')),
            ],
        ),
    ]
