# Generated by Django 5.2.1 on 2025-06-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testpointset_ac_shunt_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpointset',
            name='ac_shunt_range',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
