# Generated by Django 5.2.1 on 2026-04-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calibrationsettings_stability_check_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shunt',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvc',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
