# Generated by Django 5.2.1 on 2025-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calibrationsession_standard_tvc_serial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpoint',
            options={'ordering': ['order', 'frequency', 'current', 'direction']},
        ),
        migrations.AddField(
            model_name='testpoint',
            name='order',
            field=models.IntegerField(default=0, help_text='Custom sort order for the test point pair'),
        ),
    ]
