# Generated by Django 5.2.1 on 2025-09-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_testpoint_options_testpoint_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='ac_source_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='amplifier_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='dc_source_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='standard_reader_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='switch_driver_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_reader_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
