# Generated by Django 5.2.1 on 2025-06-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calibrationresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_ac_open_readings', models.JSONField(blank=True, default=list, null=True)),
                ('std_dc_pos_readings', models.JSONField(blank=True, default=list, null=True)),
                ('std_dc_neg_readings', models.JSONField(blank=True, default=list, null=True)),
                ('std_ac_close_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_ac_open_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_dc_pos_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_dc_neg_readings', models.JSONField(blank=True, default=list, null=True)),
                ('ti_ac_close_readings', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.calibration')),
            ],
        ),
    ]
