# Generated by Django 5.2.1 on 2026-04-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shunt_is_manual_tvc_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationconfigurations',
            name='tvc_upper_limit',
        ),
        migrations.AlterField(
            model_name='calibrationsettings',
            name='num_samples',
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationsettings',
            name='settling_time',
            field=models.IntegerField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationsettings',
            name='stability_max_attempts',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationsettings',
            name='stability_window',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
