# Generated by Django 5.2.1 on 2026-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_calibrationconfigurations_tvc_upper_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpoint',
            name='is_stability_failed',
            field=models.BooleanField(default=False),
        ),
    ]
