# Generated by Django 5.2.1 on 2025-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calibrationreadings'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='standard_instrument_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_instrument_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
