# Generated by Django 5.2.1 on 2026-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_testpoint_is_stability_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='ignore_instability_after_lock',
            field=models.BooleanField(default=False),
        ),
    ]
