# Generated by Django 5.2.1 on 2025-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calibrationsession_standard_instrument_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='ac_source_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='dc_source_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
