# Generated by Django 5.2.1 on 2025-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_calibrationsession_ac_source_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='eta_std',
            field=models.FloatField(blank=True, help_text='Gain factor for Standard instrument system', null=True),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='eta_ti',
            field=models.FloatField(blank=True, help_text='Gain factor for Test Instrument system', null=True),
        ),
        migrations.AlterField(
            model_name='calibrationsettings',
            name='num_samples',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
