# Generated by Django 5.2.1 on 2026-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_calibrationsettings_ignore_instability_after_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationreadings',
            name='std_char_minus_readings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='calibrationreadings',
            name='std_char_plus1_readings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='calibrationreadings',
            name='std_char_plus2_readings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='calibrationreadings',
            name='ti_char_minus_readings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='calibrationreadings',
            name='ti_char_plus1_readings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='calibrationreadings',
            name='ti_char_plus2_readings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
