# Generated by Django 5.2.1 on 2026-04-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_calibrationreadings_std_char_minus_readings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVCSensitivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('frequency', models.FloatField()),
                ('gain_eta', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tvc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivities', to='api.tvc')),
            ],
            options={
                'unique_together': {('tvc', 'current', 'frequency')},
            },
        ),
    ]
