# Generated by Django 5.2.1 on 2025-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_calibrationresults_eta_std_calibrationresults_eta_ti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='delta_uut_ppm',
            field=models.FloatField(blank=True, help_text='Final calculated UUT AC-DC difference in PPM', null=True),
        ),
    ]
