# Generated by Django 5.2.1 on 2025-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_calibrationresults_delta_uut_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='delta_std_known',
            field=models.FloatField(blank=True, help_text='Known AC-DC difference of the Standard Shunt in PPM', null=True),
        ),
    ]
