# Generated by Django 5.2.1 on 2025-07-07 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_calibrationresults_delta_std_known'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpointset',
            options={},
        ),
        migrations.RemoveField(
            model_name='calibrationreadings',
            name='calibration',
        ),
        migrations.RemoveField(
            model_name='calibrationresults',
            name='calibration',
        ),
        migrations.RemoveField(
            model_name='calibrationsettings',
            name='calibration',
        ),
        migrations.RemoveField(
            model_name='testpointset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testpointset',
            name='points',
        ),
        migrations.RemoveField(
            model_name='testpointset',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='amplifier_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testpointset',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_point_set', to='api.calibrationsession'),
        ),
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=5, max_digits=10)),
                ('frequency', models.IntegerField()),
                ('test_point_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.testpointset')),
            ],
        ),
        migrations.AddField(
            model_name='calibrationreadings',
            name='test_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.testpoint'),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='test_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.testpoint'),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='test_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.testpoint'),
        ),
    ]
