# Generated by Django 5.2.1 on 2026-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pendingreadingwrite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingreadingwrite',
            new_name='api_pending_status_ad873e_idx',
            old_name='api_pending_status__b6fd79_idx',
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='characterization_source',
            field=models.CharField(default='DC', max_length=10),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='characterize_std_first',
            field=models.BooleanField(default=False),
        ),
    ]
