# Generated by Django 5.2.1 on 2025-07-07 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_testpointset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationsettings',
            name='ac_shunt_range',
        ),
        migrations.RemoveField(
            model_name='calibrationsettings',
            name='amplifier_range',
        ),
        migrations.RemoveField(
            model_name='calibrationsettings',
            name='tvc_upper_limit',
        ),
        migrations.CreateModel(
            name='CalibrationConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_shunt_range', models.FloatField(blank=True, null=True)),
                ('amplifier_range', models.FloatField(blank=True, null=True)),
                ('tvc_upper_limit', models.FloatField(blank=True, null=True)),
                ('calibration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='api.calibration')),
            ],
        ),
    ]
