# Generated by Django 5.2.1 on 2026-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_api_pending_status__b6fd79_idx_api_pending_status_ad873e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('category', models.CharField(choices=[('UI/UX', 'UI/UX'), ('Hardware Communication', 'Hardware Communication'), ('Calculation Accuracy', 'Calculation Accuracy'), ('Database/Sync', 'Database/Sync'), ('Other', 'Other')], default='UI/UX', max_length=50)),
                ('description', models.TextField()),
                ('steps', models.TextField(blank=True, null=True)),
                ('system_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
