# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('In Work', 'In Work'),
                    ('Solved', 'Solved'),
                ],
                default='Not Started',
                max_length=20,
            ),
        ),
    ]
