# Generated by Django 5.2.1 on 2025-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_calibrationsettings_ac_shunt_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationsession',
            old_name='standard_instrument_address',
            new_name='standard_reader_address',
        ),
        migrations.RenameField(
            model_name='calibrationsession',
            old_name='test_instrument_address',
            new_name='standard_reader_model',
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_reader_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='test_reader_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
