# Generated by Django 5.2.1 on 2025-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_standard_instrument_address_calibrationsession_standard_reader_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpoint',
            options={'ordering': ['frequency', 'current', 'direction']},
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='settling_time',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='testpoint',
            name='direction',
            field=models.CharField(choices=[('Forward', 'Forward'), ('Reverse', 'Reverse')], default='Forward', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='testpoint',
            unique_together={('test_point_set', 'current', 'frequency', 'direction')},
        ),
    ]
