# Generated by Django 5.2.1 on 2025-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_testpoint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.FloatField()),
                ('current', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('correction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('range', 'current', 'frequency')},
            },
        ),
        migrations.CreateModel(
            name='Uncertainty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.FloatField()),
                ('current', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('range', 'current', 'frequency')},
            },
        ),
    ]
