# Generated by Django 5.2.1 on 2026-04-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_characterize_std_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('identifier', models.SlugField(help_text='Stable slug used in URLs / WebSocket payloads. Lower-case, no spaces.', max_length=100, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marks the auto-created local bench. Used as the fallback workstation when a CalibrationSession has no explicit link.')),
                ('instrument_addresses', models.JSONField(blank=True, default=list, help_text='Advisory list of GPIB/VISA addresses that physically live at this bench. Not enforced at run-time — used by the UI to pre-filter instrument choices when configuring a session.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.workstation'),
        ),
        migrations.CreateModel(
            name='WorkstationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_channel', models.CharField(db_index=True, max_length=200)),
                ('owner_client_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner_label', models.CharField(blank=True, default='', help_text='Human-readable owner description surfaced in the UI.', max_length=200)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(auto_now=True)),
                ('active_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_claims', to='api.calibrationsession')),
                ('workstation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='api.workstation')),
            ],
            options={
                'indexes': [models.Index(fields=['owner_channel'], name='api_worksta_owner_c_f01376_idx'), models.Index(fields=['last_heartbeat_at'], name='api_worksta_last_he_b9ffcc_idx')],
            },
        ),
    ]
