# Generated by Django 5.2.1 on 2026-05-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_workstation_and_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='cycles_to_average',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='lf_harmonic_projection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='low_frequency_ac_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='min_low_freq_settling_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
