# Generated by Django 5.2.1 on 2025-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_correction_uncertainty'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='delta_uut_ppm_avg',
            field=models.FloatField(blank=True, help_text='Final averaged UUT AC-DC difference in PPM', null=True),
        ),
        migrations.AlterField(
            model_name='calibrationresults',
            name='delta_uut_ppm',
            field=models.FloatField(blank=True, help_text='Final calculated UUT AC-DC difference in PPM -> Forward or Revers', null=True),
        ),
    ]
