# Generated by Django 5.2.1 on 2025-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calibrationresults_delta_uut_ppm_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='combined_uncertainty',
            field=models.FloatField(blank=True, help_text='Calculated combined standard uncertainty (uc) in PPM', null=True),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='effective_dof',
            field=models.FloatField(blank=True, help_text='Calculated effective degrees of freedom (veff)', null=True),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='expanded_uncertainty',
            field=models.FloatField(blank=True, help_text='Calculated expanded uncertainty (U) in PPM', null=True),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='is_detailed_uncertainty_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='k_value',
            field=models.FloatField(blank=True, help_text='Calculated coverage factor (k)', null=True),
        ),
    ]
