# Generated by Django 5.2.1 on 2026-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calibrationsettings_cycles_to_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationsettings',
            name='low_frequency_ac_mode',
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='enable_11hz_filter',
            field=models.BooleanField(default=True),
        ),
    ]
