# Generated by Django 5.2.1 on 2026-05-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_calibrationsettings_low_frequency_ac_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationsettings',
            name='cycles_to_average',
        ),
    ]
