# Generated by Django 5.2.1 on 2025-07-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_calibrationresults_combined_uncertainty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='manual_uncertainty_components',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
