# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_calibrationsettings_cycles_to_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='enable_low_frequency_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='lf_harmonics',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
