# Generated by Django 5.2.1 on 2025-08-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_calibrationresults_manual_uncertainty_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='switch_driver_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='switch_driver_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
