# Generated by Django 5.2.1 on 2025-08-01 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_calibrationresults_manual_uncertainty_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='delta_std',
            field=models.FloatField(blank=True, help_text='Known AC-DC difference of the Standard TVC in PPM', null=True),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='delta_ti',
            field=models.FloatField(blank=True, help_text='Known AC-DC difference of the TI TVC in PPM', null=True),
        ),
        migrations.CreateModel(
            name='CalibrationTVCCorrections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrections_data', models.JSONField(blank=True, default=dict)),
                ('calibration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tvccorrections', to='api.calibration')),
            ],
        ),
    ]
