# Generated by Django 5.2.1 on 2026-05-13 01:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_calibrationsettings_enable_low_frequency_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationresults',
            name='type_a_uncertainty_ppm',
            field=models.FloatField(blank=True, help_text='Type A standard uncertainty u_A = s(δᵢ)/√N in PPM, computed from per-cycle δ values.', null=True),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='n_cycles',
            field=models.PositiveIntegerField(default=3, help_text='Number of full AC-DC cycles to average per test point (>= 2).', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='calibrationresults',
            name='delta_uut_ppm',
            field=models.FloatField(blank=True, help_text='Legacy single-pass UUT AC-DC difference in PPM (pre-N-cycle workflow)', null=True),
        ),
        migrations.AlterField(
            model_name='calibrationresults',
            name='delta_uut_ppm_avg',
            field=models.FloatField(blank=True, help_text='Mean δ across N cycles (x̄) in PPM — the value compared against spec', null=True),
        ),
        migrations.CreateModel(
            name='CalibrationResultsCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_index', models.PositiveIntegerField(help_text='1-based cycle ordinal within a test point.')),
                ('delta_uut_ppm', models.FloatField(blank=True, help_text='δ_UUT for this cycle alone, in PPM.', null=True)),
                ('std_ac_open_avg', models.FloatField(blank=True, null=True)),
                ('std_dc_pos_avg', models.FloatField(blank=True, null=True)),
                ('std_dc_neg_avg', models.FloatField(blank=True, null=True)),
                ('std_ac_close_avg', models.FloatField(blank=True, null=True)),
                ('ti_ac_open_avg', models.FloatField(blank=True, null=True)),
                ('ti_dc_pos_avg', models.FloatField(blank=True, null=True)),
                ('ti_dc_neg_avg', models.FloatField(blank=True, null=True)),
                ('ti_ac_close_avg', models.FloatField(blank=True, null=True)),
                ('std_ac_open_stddev', models.FloatField(blank=True, null=True)),
                ('std_dc_pos_stddev', models.FloatField(blank=True, null=True)),
                ('std_dc_neg_stddev', models.FloatField(blank=True, null=True)),
                ('std_ac_close_stddev', models.FloatField(blank=True, null=True)),
                ('ti_ac_open_stddev', models.FloatField(blank=True, null=True)),
                ('ti_dc_pos_stddev', models.FloatField(blank=True, null=True)),
                ('ti_dc_neg_stddev', models.FloatField(blank=True, null=True)),
                ('ti_ac_close_stddev', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='api.calibrationresults')),
            ],
            options={
                'ordering': ['cycle_index'],
                'unique_together': {('results', 'cycle_index')},
            },
        ),
    ]
