# Generated by Django 5.2.1 on 2025-08-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_calibrationresults_delta_std_and_more'),
        ('api', '0020_calibrationsession_switch_driver_address_and_more'),
    ]

    operations = [
    ]
