# Generated by Django 5.2.1 on 2025-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20250811_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='nplc',
            field=models.FloatField(blank=True, default=20, help_text='Integration time in Power Line Cycles for 34420A', null=True),
        ),
    ]
