# Generated by Django 5.2.1 on 2026-05-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_calibrationresults_type_a_uncertainty_ppm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationconfigurations',
            name='use_abba_pairing',
            field=models.BooleanField(default=True, help_text='When true, reverse-pair Fwd_i with Rev_{N+1-i} so linear drift across the run cancels. When false, index-pair Fwd_i with Rev_i. Toggle for testing/comparison.'),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='pair_delta_uut_ppm',
            field=models.FloatField(blank=True, help_text='Paired AC-DC δ_UUT = mean over pair_i = (δ_Fwd_i + δ_Rev_{N+1-i})/2 (ppm). Mirrored on both Fwd and Rev results rows.', null=True),
        ),
        migrations.AddField(
            model_name='calibrationresults',
            name='pair_type_a_uncertainty_ppm',
            field=models.FloatField(blank=True, help_text='Pair-level Type A u_A = s(pair_δ_i)/√N (ppm). Mirrored on both Fwd and Rev results rows.', null=True),
        ),
        migrations.AlterField(
            model_name='calibrationresults',
            name='delta_uut_ppm_avg',
            field=models.FloatField(blank=True, help_text="Per-direction mean δ across this TestPoint's cycles (ppm). Diagnostic only — the headline AC-DC δ is pair_delta_uut_ppm.", null=True),
        ),
        migrations.AlterField(
            model_name='calibrationresults',
            name='type_a_uncertainty_ppm',
            field=models.FloatField(blank=True, help_text="Per-direction Type A u_A = s(δᵢ)/√N across this TestPoint's cycles (ppm). Diagnostic only — the headline u_A is pair_type_a_uncertainty_ppm.", null=True),
        ),
    ]
