# Generated by Django 5.2.1 on 2025-08-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_calibrationsettings_nplc'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='amplifier_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
