# Generated by Django 5.2.1 on 2025-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_calibrationsession_amplifier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='stability_threshold_ppm',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsettings',
            name='stability_window',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
