# Generated by Django 5.2.1 on 2025-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_calibrationsettings_stability_threshold_ppm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='stability_max_attempts',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
