# Generated by Django 5.2.1 on 2026-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_shunt_unique_with_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationsettings',
            name='ignore_instability_after_lock',
            field=models.BooleanField(default=True),
        ),
    ]
