# Generated by Django 5.2.1 on 2026-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_default_ignore_instability_after_lock_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsettings',
            name='characterize_std_first',
            field=models.BooleanField(default=False),
        ),
    ]
