# Generated by Django 5.2.1 on 2026-06-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_calibrationsettings_characterize_std_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='visa_host',
            field=models.CharField(blank=True, default='', help_text="NI-VISA remote server host for this bench (configured in NI MAX -> Remote Systems), e.g. '10.0.0.42'. When set, the central VM opens this bench's instruments remotely as visa://<host>/<address>. Blank means the instruments are local to the server process.", max_length=200),
        ),
    ]
