# Generated by Django 5.2.1 on 2026-06-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_workstation_visa_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRunLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_channel', models.CharField(db_index=True, max_length=200)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_locks', to='api.calibrationsession')),
                ('workstation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_lock', to='api.workstation')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='api_calibra_session_34567c_idx'), models.Index(fields=['last_heartbeat_at'], name='api_calibra_last_he_4955b6_idx')],
            },
        ),
    ]
